### ISSUE TITLE
Is it possible to have 2 <val-default-errors>?

### ISSUE THREAD

**Issue by david-bulte** [Ninja-Squad/ngx-valdemort#260]
I'm thinking of a scenario where a module comes with its own specific defaults. It would be handy if these specific defaults could be merged with the ones defined in the root component.

Is this something you'd consider? Is there a workaround (apart from providing all error messages in the root)?

**Comment by jnizet** [comment]
Hi David.

I understand that some errors are specific to a feature module, and that, ideally, the root module shouldn't care about them.
However, given the tiny amount of additional load that it requires to define a few additional default error messages, I wouldn't bother, and would keep things simple by defining them all in the same place.

There could be a workaround: the default error directives are stored in a service (provided in root by default). So, unless I miss something, if you explicitely provide this service in a lazy-loaded module, and also add a `<val-default-errors>` in some root component of that module, then all the components of that module should use the module-specific default errors. Using some nasty injection tricks, there might even be a way of merging those error directives with the ones from the root module. However, that service is not part of the public API, and I really think this would make things much more complex for a tiny gain. So I would stick to my recommendation of setting them all in the root module.

Merging new error directives to the existing ones when lazy-loading a module would also not be so easy:
- what if two modules provide a default error for the same type of error? 
- how to deal with the order of the error messages?
- since a lazy-loaded root component can be destroyed and re-created, how would we re-merge its default error messages
- should the default error messages of a module be removed if the component which set them is destroyed?

All these problems don't exist if you store everything at the root.

**Comment by david-bulte** [comment]
Thanks for your answer, I do appreciate the simplicity of the library.
